{{- if .Values.secret.s3 }}
{{- if not .Values.secret.s3.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase-ha.secret.s3" . }}
  labels:
    {{- include "supabase-ha.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.s3 }}
{{- if $value }}
{{- if eq (typeOf $value) "string" }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
