# ============================================================
# EXAMPLE TEMPLATE - Production (3 nodes)
# ============================================================
# Customize for your environment:
#   - dockerImage (if using custom registry)
#   - storageClass
#   - resources (CPU/memory based on workload)
#   - backup configuration (S3 bucket, endpoint, credentials)
# ============================================================

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: supabase-db
  namespace: supabase  # TODO: Change if using different namespace
  labels:
    app: supabase
    component: database
spec:
  teamId: "supabase"
  version: "17"
  numberOfInstances: 3  # 1 primary + 2 replicas

  # Spilo Supabase image
  dockerImage: klosowsk/spilo-supabase:17-latest  # TODO: Change to your registry if needed

  # Resources per pod
  resources:
    requests:
      cpu: 1000m      # TODO: Adjust based on workload
      memory: 2Gi     # TODO: Adjust based on workload
    limits:
      cpu: 2000m
      memory: 4Gi

  # Storage
  volume:
    size: 50Gi                # TODO: Adjust size for your data
    storageClass: standard    # TODO: Change to your storage class

  # Supabase roles (auto-created by operator)
  # Passwords stored in secrets: {username}.supabase-db.credentials.postgresql.acid.zalan.do
  users:
    supabase_admin:
      - superuser
      - createdb
      - createrole
      - replication
      - bypassrls
    service_role:
      - bypassrls
    authenticator: []
    supabase_auth_admin:
      - createrole
    supabase_storage_admin:
      - createrole
    supabase_functions_admin:
      - createrole
    supabase_replication_admin:
      - replication
    supabase_read_only_user:
      - bypassrls
    anon: []
    authenticated: []

  databases:
    postgres: supabase_admin

  # PostgreSQL configuration
  postgresql:
    version: "17"
    parameters:
      # Required: Supabase extensions
      shared_preload_libraries: "timescaledb,pgsodium,pg_cron,pg_net,pg_stat_statements,auto_explain,pg_wait_sampling,pg_tle,plan_filter"
      cron.database_name: "postgres"

      # Required: Realtime/replication
      wal_level: "logical"
      max_wal_senders: "10"
      max_replication_slots: "10"

      # Performance tuning
      max_connections: "200"
      shared_buffers: "512MB"       # TODO: Tune based on RAM (25% of memory)
      effective_cache_size: "1536MB" # TODO: Tune based on RAM (75% of memory)
      work_mem: "5MB"
      maintenance_work_mem: "128MB"

      # Logging
      log_min_duration_statement: "1000"  # Log queries > 1s
      log_statement: "ddl"

  # Patroni HA configuration
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    synchronous_mode: true
    synchronous_mode_strict: false

  # Connection pooler (recommended for Supabase)
  connectionPooler:
    numberOfInstances: 2
    mode: "transaction"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi

  # Backup configuration
  # Create secret: kubectl create secret generic backup-s3-credentials \
  #   --from-literal=access-key-id=YOUR_KEY \
  #   --from-literal=secret-access-key=YOUR_SECRET \
  #   -n supabase
  env:
    - name: WAL_S3_BUCKET
      value: "supabase-postgres-backups"  # TODO: Change to your bucket name

    - name: AWS_ENDPOINT
      value: "https://s3.amazonaws.com"  # TODO: Change to your S3/MinIO endpoint

    - name: AWS_REGION
      value: "us-east-1"  # TODO: Change to your region

    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: backup-s3-credentials
          key: access-key-id

    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: backup-s3-credentials
          key: secret-access-key

    - name: BACKUP_SCHEDULE
      value: "0 2 * * *"  # Daily at 2 AM

    - name: USE_WALG_RESTORE
      value: "true"

    - name: WALG_COMPRESSION_METHOD
      value: "zstd"

    - name: WALG_DELTA_MAX_STEPS
      value: "14"  # Keep 14 days of backups
