{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase-ha.fullname" . }}-jwt-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: supabase
    component: database-config
    {{- include "supabase-ha.labels" . | nindent 4 }}
  annotations:
    # Ensure this secret is created before the PostgreSQL cluster
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  # JWT secret used by Supabase services
  # This MUST match secret.jwt.secret value
  JWT_SECRET: {{ required "secret.jwt.secret is required" .Values.secret.jwt.secret | b64enc | quote }}
  JWT_EXP: {{ .Values.postgresql.jwtExp | default "3600" | toString | b64enc | quote }}
{{- end }}
