apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default namespace for all resources
# Override this in overlays for different environments
namespace: default

# Generate ConfigMap from SQL files
# These files are created by: ./scripts/generate-configmaps.sh
configMapGenerator:
- name: supabase-master-init
  files:
  - init-sql/00-master-init.sql
  - init-sql/01-custom-init.sql
  - init-sql/02-supabase-init.sql
  - init-sql/03-supabase-migrations.sql
  options:
    labels:
      app: supabase-db
      component: initialization

# CloudNativePG Cluster manifest
resources:
- cluster.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: supabase-db
  app.kubernetes.io/managed-by: kustomize
