-- Supabase Master Initialization Script for CloudNativePG
-- This script orchestrates all Supabase migrations and initialization
-- Auto-generated by scripts/generate-configmaps.sh

\set ON_ERROR_STOP on

-- Validate required environment variables
DO $$
BEGIN
  IF current_setting('supabase.jwt_secret', true) IS NULL THEN
    RAISE EXCEPTION 'JWT_SECRET environment variable is required';
  END IF;
EXCEPTION WHEN undefined_object THEN
  RAISE EXCEPTION 'JWT_SECRET must be set via postgresql.parameters in Cluster manifest';
END $$;

\echo '===================================='
\echo 'Supabase Initialization Started'
\echo '===================================='
\echo ''

-- Create postgres role if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'postgres') THEN
    CREATE ROLE postgres SUPERUSER LOGIN;
    RAISE NOTICE 'Created postgres superuser role';
  END IF;
END $$;

-- Ensure supabase_admin exists and is superuser
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'supabase_admin') THEN
    CREATE ROLE supabase_admin SUPERUSER LOGIN;
    RAISE NOTICE 'Created supabase_admin role';
  ELSE
    ALTER ROLE supabase_admin SUPERUSER;
  END IF;
END $$;

\echo ''
\echo 'Phase 1: Custom Init Scripts'
\echo '----------------------------'
\ir 01-custom-init.sql

\echo ''
\echo 'Phase 2: Supabase Init Scripts'
\echo '-------------------------------'
\ir 02-supabase-init.sql

\echo ''
\echo 'Phase 3: Supabase Migrations'
\echo '-----------------------------'
\ir 03-supabase-migrations.sql

\echo ''
\echo '===================================='
\echo '✅ Supabase Initialization Complete!'
\echo '===================================='
