name: Build and Push

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract PostgreSQL version from tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            PG_MAJOR=$(echo $VERSION | cut -d. -f1)
            echo "pg_major=${PG_MAJOR}" >> $GITHUB_OUTPUT
          else
            echo "pg_major=15" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: klosowsk/cloudnativepg-supabase
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: klosowsk/cloudnativepg-supabase:test
          load: true
          build-args: |
            PG_MAJOR=${{ steps.version.outputs.pg_major }}

      - name: Test image
        run: |
          echo "=== Verifying image built successfully ==="
          docker images | grep cloudnativepg-supabase

          echo "=== Checking PostgreSQL version ==="
          docker run --rm klosowsk/cloudnativepg-supabase:test postgres --version

          echo "=== Verifying extensions are installed ==="
          docker run --rm klosowsk/cloudnativepg-supabase:test dpkg -l | grep postgresql-${{ steps.version.outputs.pg_major }} | head -20

      - name: Push to registry
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PG_MAJOR=${{ steps.version.outputs.pg_major }}
